services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-7861}:${PORT:-7861}"  #  Use environment variable, fallback to 7861
    environment:
      PORT: "${PORT:-7861}"  #  Set the PORT environment variable inside the container
    restart: unless-stopped
